"""Create user table

Revision ID: 08c2534918f9
Revises: f0572c0765a2
Create Date: 2021-05-04 01:28:37.698445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c2534918f9'
down_revision = 'f0572c0765a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
