"""Create user table

Revision ID: 18d91aad6c1f
Revises: 5e881b935ab0
Create Date: 2021-05-04 01:30:37.855454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d91aad6c1f'
down_revision = '5e881b935ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
