"""Create user table

Revision ID: 25ea026ed1b3
Revises: eccd8bf3c3f8
Create Date: 2021-05-04 03:08:33.822017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ea026ed1b3'
down_revision = 'eccd8bf3c3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
