"""Create user table

Revision ID: 270c9969ea39
Revises: 18d91aad6c1f
Create Date: 2021-05-04 01:33:17.063784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270c9969ea39'
down_revision = '18d91aad6c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
