"""Create user table

Revision ID: 46e0180751fc
Revises: 9311a0b437b6
Create Date: 2021-05-04 03:57:06.947577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e0180751fc'
down_revision = '9311a0b437b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
