"""Create user table

Revision ID: 53012f945bd9
Revises: 46e0180751fc
Create Date: 2021-05-06 12:26:18.815880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53012f945bd9'
down_revision = '46e0180751fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
