"""Create user table

Revision ID: 5e881b935ab0
Revises: 08c2534918f9
Create Date: 2021-05-04 01:29:15.729392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e881b935ab0'
down_revision = '08c2534918f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
