"""Create user table

Revision ID: 96d5215190f7
Revises: ddaef633ce8c
Create Date: 2021-05-03 23:58:00.845321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d5215190f7'
down_revision = 'ddaef633ce8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
