"""Create user table

Revision ID: cc1a1d7d1970
Revises: 0b263a938e76
Create Date: 2021-05-04 02:03:58.723672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1a1d7d1970'
down_revision = '0b263a938e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
