"""Create user table

Revision ID: eccd8bf3c3f8
Revises: cc1a1d7d1970
Create Date: 2021-05-04 02:44:51.699770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccd8bf3c3f8'
down_revision = 'cc1a1d7d1970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
